// scripts/vendor-fonts.mjs
// Downloads the Google Fonts the app uses into public/fonts and writes a local
// stylesheet with the same family names, so pages never depend on
// fonts.googleapis.com at runtime (a hanging font request blocks first paint).
// Run once with `npm run vendor:fonts`; commit the output.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const CSS_URL = 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&family=DM+Sans:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500;600&family=Inter:wght@400;500;600;700;800&display=swap';
const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'fonts');
mkdirSync(out, { recursive: true });

// A modern browser UA makes Google serve woff2 with unicode-range subsets.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
let css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

const urls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]))];
for (const url of urls) {
  const name = url.split('/').slice(-2).join('-');
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed ${url}: ${res.status}`);
  writeFileSync(join(out, name), Buffer.from(await res.arrayBuffer()));
  css = css.split(url).join(`/fonts/${name}`);
}
writeFileSync(join(out, 'fonts.css'), `/* Generated by scripts/vendor-fonts.mjs from Google Fonts. */\n${css}`);
console.log(`Vendored ${urls.length} font files into public/fonts`);
